Composites documentation
autofac/Documentation pull request #105
Opened 2020-07-02 08:15 UTC by alistairjevans

Initial go at documentation for the new composites feature.

I've created a new v6 branch in the documentation repo to target for this, we can merge that into master when v6 ships.

2020-07-02 14:23 UTC, tillig requested changes
Couple minor things, otherwise this is great.

I have this feeling in the back of my head that there will be folks who assume Autofac will also do _something_ [unquantified] about error handling with the composites. Like, "I did the foreach over the collection and one of them threw an exception. Dammit, Autofac, Y U NO MAGIC?" But it also seems redundant to have to specify, "Hey, you're writing this composite, it's up to _you_ to control how it works."

2020-07-02 14:23 UTC, tillig commented on docs/advanced/composites.rst
> +This functionality is particularly useful if you find yourself needing to add an additional provider for a service, but you
```suggestion
This functionality is particularly useful if you find yourself needing to add a provider for a service, but you
```

2020-07-02 14:23 UTC, tillig commented on docs/advanced/composites.rst
> +implications of making composite registration's long-living; a `SingleInstance` composite would ignore any additional registrations
```suggestion
implications of making composite registration's long-living; a ``SingleInstance`` composite would ignore any additional registrations
```

2020-07-03 05:28 UTC, alistairjevans commented on docs/advanced/composites.rst
> +implications of making composite registration's long-living; a `SingleInstance` composite would ignore any additional registrations
Also noticed that incorrect apostrophe.

2020-07-03 05:30 UTC, alistairjevans commented
Since we're making people write their own wrapper, we're mostly minimising the amount of magic we're actually doing.  It might be different if we were providing an automatic 'this composite wrapper automatically calls all your providers in a foreach'. Then we would need to worry about that error handling.

2020-07-03 05:44 UTC, tillig approved these changes
:tada:

2020-07-03 05:44 UTC, merged