Feature/948 document immutable component registry
autofac/Documentation pull request #84
Opened 2019-09-12 11:05 UTC by weelink

This PR for updating the documentation regarding the changes done for https://github.com/autofac/Autofac/pull/981 (making `ComponentRegistry` immutable).

I also removed references to updating the container.

2019-09-12 15:30 UTC, tillig requested changes
Other than one minor change, this looks good. Thanks for following up here.

I guess I hadn't realized `ComponentRegistry` had become non-public. Good changes, to be sure, just something I hadn't noticed.

2019-09-12 15:30 UTC, tillig commented on docs/advanced/concurrency.rst
> +``ContainerBuilder`` and ``ComponentRegistryBuilder`` **are not thread-safe** and is designed to be used only on a single thread at the time the application starts up. This is the most common scenari
"...and are designed..." rather than "...and is designed..."

2019-09-12 15:33 UTC, tillig commented
(Admittedly, we may hold off on merging this into the docs until we pull the Autofac `pr-immutable-container` branch into `develop`, but otherwise, yay!)

2019-09-16 07:29 UTC, weelink commented on docs/advanced/concurrency.rst
> +``ContainerBuilder`` and ``ComponentRegistryBuilder`` **are not thread-safe** and is designed to be used only on a single thread at the time the application starts up. This is the most common scenari
Nice catch. I missed that one.

2019-09-16 16:23 UTC, tillig approved these changes
:tada:

2019-12-21 15:03 UTC, alexmg commented
The `pr-immutable-container` branch has now been merged into `develop`. I think we should wait until the changes are available in a proper release before updating the documentation.

2020-01-30 23:16 UTC, tillig commented
Ready to merge!

2020-01-30 23:16 UTC, merged